---
- name: Lấy thông tin IP của các thiết bị Cisco
  hosts: all
  tasks:
    - name: Lấy thông tin về các thiết bị Cisco
      ios_facts:
      register: ios_facts_result

    - name: Hiển thị thông tin về IP của các thiết bị
      debug:
        msg: "Địa chỉ IP của thiết bị {{ item.key }} là {{ item.value.ansible_net_all_ipv4_addresses }}"
      loop: "{{ ios_facts_result.ansible_facts }}"
      loop_control:
        label: "{{ item.key }}"
