---
- name: Lấy thông tin IP của các thiết bị Cisco
  hosts: cisco_routers
  tasks:
    - name: Lấy thông tin về các thiết bị Cisco
      ios_facts:
      register: ios_facts_result

    - name: Hiển thị thông tin về IP của các thiết bị
      debug: 
        msg: "Địa chỉ IP của thiết bị {{ item.key }} là {{ item.value.ipv4 }}"
      loop: "{{ ios_facts_result.ansible_facts['ansible_net_all_ipv4_addresses'] | dict2items }}"
