---
- name: Lấy running config của các thiết bị Cisco
  hosts: cisco_routers
  tasks:
    - name: Lấy running config
      ios_config:
        src: running
      register: running_config

    - name: Hiển thị running config
      debug:
        msg: "{{ running_config }}"
